m2mkwt/m2m-lecture-demo-frontend

package.json
tailwind.config.js

게시물 본문 텍스트 3줄 이상일 때 말줄임(ellipsis) 표시 처리 패키지  추가하였습니다.

FEAT: line-clamp 플러그인 추가

---

src/components/ProfileEdit.vue

프로필 수정을 위한 소스 수정

---

src/view/SignUpForm.vue

SignUpForm.vue 수정
- 변경된 uri 적용
- /api/v1/member/registMember 호출 시 success면 로그인 화면으로 이동 그 외 alert 적용

FIX: 회원가입 폼 수정

---

src/store/index.js

FIX: index.js 변경

---

src/view/MyPage.vue

MyPage.vue 수정
- 내가 작성한 게시물 리스트 조회 기능 추가

FIX: 마이페이지 수정

---

src/components/layout/TheHeader.vue

TheHeader.vue 수정
헤더의 드롭다운 메뉴에서 로그아웃 클릭시 로그인 페이지로 이동

FIX: 헤더 로그아웃 기능 추가

---

src/components/layout/TheHeader.vue

Theader.vue 수정
- 프로필 → 마이페이지로 수정

FIX: 헤더 수정

---

src/components/post/Post.vue
src/view/HomePage.vue

Post.vue
- 내가 작성한 게시물일 때만 ... 보이도록 수정
HomePage.vue
- Post.vue 로 memberNo 넘겨주도록 수정

FIX: 홈페이지 수정

---

src/components/layout/TheHeader.vue

게시글 작성 시 이미지 업로드 적용

---

src/components/comment/Comment.vue
src/components/post/Post.vue

- Computed : dateFormat 함수 추가
- 게시물 상세 모달 ui 수정 2차

FEAT: 게시물 DateFormat computed 추가

---

src/view/ProfileEdit.vue

유효성 검사 : 아이디 중복 체크 수정

---

src/components/post/Post.vue

- 게시물 수정 버튼 클릭시 Modal창 Close
- 댓글 submit 후엔 댓글창 clear

FIX: 게시물 수정시 Modal창 닫기 & 댓글 submit 후 댓글 창 clear

---

src/components/post/Post.vue
src/view/MyPage.vue

- 마이페이지 modal에 commentList 출력
- [UI] Post.vue border-right 값 넣음

FEAT: 마이페이지 Modal에 commentList 출력

---

src/view/ProfileEdit.vue

FIX: 프로필 편집 페이지 수정

---

.gitignore
src/components/post/Post.vue
src/view/HomePage.vue

좋아요 기능 적용 등 수정 (변경점 많아서 확인 후 나중에 병합 필요), .gitignore에 public/upload 제거

---

src/components/layout/TheHeader.vue

FIX: 게시글 작성 모달 대체이미지 적용

---

src/components/post/Post.vue

FIX: 게시물 상세페이지 모달 대체이미지 적용

---

src/components/comment/Comment.vue

FIX: 댓글 대체이미지 적용

---

src/components/comment/Comment.vue

FIX: 모달창 내부 댓글 수정/삭제 버튼 조정

---

src/view/MyPage.vue

FIX: 미사용 코드 정리
